# Generated by Django 2.0.8 on 2018-09-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_auto_20180904_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerpage',
            old_name='hero_image',
            new_name='profile_image',
        ),
    ]
