language: python
python: "3.6"
cache:
  pip: true


# Use container-based infrastructure
dist: trusty
sudo: false


env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.dev

install:
  - pip install wheel
  - pip install -r requirements.txt

script:
  # Code style, missing imports, etc
  - flake8 wagtail_freelancer
  - isort --check-only --diff --recursive wagtail_freelancer --skip-glob "*/migrations/*"

  # Run system checks
  - python manage.py check

  # Check for missing migrations
  - python manage.py makemigrations --check
