# Generated by Django 2.0.8 on 2018-09-04 04:43

from django.db import migrations


def create_homepage(apps, schema_editor):
    # Delete the automatically created "Welcome" page
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore', 'Page')
    Site = apps.get_model('wagtailcore', 'Site')
    FreelancerPage = apps.get_model('freelancer', 'FreelancerPage')

    # Delete the default homepage (also deletes the default Site)
    Page.objects.get(url_path='/home/').delete()

    content_type, _ = ContentType.objects.get_or_create(app_label='freelancer', model='freelancerpage')

    freelancerpage = FreelancerPage(
        title='Freelancer',
        slug='freelancer',
        content_type=content_type,
        path='00010001',
        depth=2,
        numchild=0,
        url_path='/freelancer/',
    )
    freelancerpage.save()

    Site.objects.create(hostname='localhost', root_page=freelancerpage, is_default_site=True)


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_homepage)
    ]
